### ISSUE TITLE
EspSaveCrash and custom saving to EEPROM

### ISSUE THREAD

**Issue by bineagu** [krzychb/EspSaveCrash#14]
Hello, 

It looks like after adding EspSaveCrash, I cannot save to EEPROM like my code used to do. Is there a special way work with the memory in both ways?

I have this configuration:
`EspSaveCrash SaveCrash(2560, 1024);`

And after that, in the setup function I use:
`EEPROM.begin(2048);
 EEPROM.get(0, settings);`

and later in the code 
`EEPROM.put(0, settings);
  EEPROM.commit();`

but after a reboot the settings struct doesn't hold the new saved settings. Any idea?

Thanks.

**Comment by mano3m** [comment]
This is because the values used in the callback function which stores the data in eeprom use hard-coded variables... I think this is unintended / the author tried to used the variables from a c++ class in a c style callback and hard-coded the two variables in a namespace instead of the class... To fix, change the hard-coded values in the .cpp file to be normal global variables and change the value of those when a classobject is initialized.

**Comment by bwjohns4** [comment]
Did you ever figure out how to use this while also using EEPROM separately in your app?

**Comment by bwjohns4** [comment]
Troubleshooting it in my code revealed that the EEPROM.end() within EspSaveCrash was closing the EEPROM that my app was using so after any calls to EspSaveCrash.print() or .clear() then my EEPROM would be closed and no subsequent usage of EEPROM in my app was valid to read nor would it actually write. I replaced the .end() calls with .commit() and it now works with my app.

**Comment by krzychb** [comment]
A fix by @bwjohns4 is provided in #15!

**Comment by krzychb** [comment]
The fix has been merged to master in 438f2c0c84145822a03a7f2aedb439a755a800be. Thank you @bwjohns4!
